### ISSUE TITLE
(1/1) UnexpectedValueExceptionThe stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

### ISSUE THREAD

**Issue by sistemmsn** [ziishaned/opus#123]
(1/1) UnexpectedValueExceptionThe stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
--
in StreamHandler.php line 107
at StreamHandler->write(array('message' => 'UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-06-11 23:51:08] local.ERROR: UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in AbstractProcessingHandler.php line 39
at AbstractProcessingHandler->handle(array('message' => 'UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-06-11 23:51:08] local.ERROR: UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\\Log\\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in Logger.php line 344
at Logger->addRecord(400, object(UnexpectedValueException), array())in Logger.php line 707
at Logger->error(object(UnexpectedValueException), array())in Writer.php line 203
at Writer->writeLog('error', object(UnexpectedValueException), array())in Writer.php line 114
at Writer->error(object(UnexpectedValueException))in Handler.php line 71
at Handler->report(object(UnexpectedValueException))in Handler.php line 35
at Handler->report(object(UnexpectedValueException))in HandleExceptions.php line 81
at HandleExceptions->handleException(object(UnexpectedValueException))

**Comment by misaelbg** [comment]
> ## (1/1) UnexpectedValueExceptionThe stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
> in StreamHandler.php line 107
> at StreamHandler->write(array('message' => 'UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\Log\Writer->writeLog('error', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\Log\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\Foundation\Exceptions\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\Exceptions\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Foundation\Http\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-06-11 23:51:08] local.ERROR: UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\Log\Writer->writeLog('error', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\Log\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\Foundation\Exceptions\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\Exceptions\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Foundation\Http\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))#10 {main} '))in AbstractProcessingHandler.php line 39
> at AbstractProcessingHandler->handle(array('message' => 'UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\Log\Writer->writeLog('error', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\Log\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\Foundation\Exceptions\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\Exceptions\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Foundation\Http\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'local', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-06-11 23:51:08] local.ERROR: UnexpectedValueException: The stream or file "/var/www/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107Stack trace:#0 /var/www/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)#1 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)#2 /var/www/vendor/monolog/monolog/src/Monolog/Logger.php(707): Monolog\Logger->addRecord(400, Object(Exception), Array)#3 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\Logger->error(Object(Exception), Array)#4 /var/www/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\Log\Writer->writeLog('error', Object(Exception), Array)#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(71): Illuminate\Log\Writer->error(Object(Exception))#6 /var/www/app/Exceptions/Handler.php(35): Illuminate\Foundation\Exceptions\Handler->report(Object(Exception))#7 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\Exceptions\Handler->report(Object(Exception))#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Foundation\Http\Kernel->reportException(Object(Exception))#9 /var/www/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))#10 {main} '))in Logger.php line 344
> at Logger->addRecord(400, object(UnexpectedValueException), array())in Logger.php line 707
> at Logger->error(object(UnexpectedValueException), array())in Writer.php line 203
> at Writer->writeLog('error', object(UnexpectedValueException), array())in Writer.php line 114
> at Writer->error(object(UnexpectedValueException))in Handler.php line 71
> at Handler->report(object(UnexpectedValueException))in Handler.php line 35
> at Handler->report(object(UnexpectedValueException))in HandleExceptions.php line 81
> at HandleExceptions->handleException(object(UnexpectedValueException))

I opened a new PR with the correction!  --> https://github.com/ziishaned/opus/pull/138
You can download the "Fix release" on my fork. --> https://github.com/misaelbg/opus
I will try to correct as many issues as possible and I will open PR in the next few days.
